{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "testfront.serviceAccountName" . }}
  labels:
{{ include "testfront.labels" . | indent 4 }}
{{- end -}}
