apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "testback.fullname" . }}-varsenv
  labels:
    app: {{ template "testback.name" . }}
    chart: {{ template "testback.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{.Files.Get "files/.env" | printf "%s" | replace "=" ": " | indent 2}}        
