{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "testback.serviceAccountName" . }}
  labels:
{{ include "testback.labels" . | indent 4 }}
{{- end -}}
